version: "3.8"
services: 
  spa:
    restart: always
    build: 
      context: ./spa
      dockerfile: Dockerfile
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./spa:/usr/app
    ports: 
      - "3000:3000"
    depends_on: 
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"